pipeline {
    agent any
    parameters {
        string(name: 'AWS_CREDENTIAL_ID', defaultValue: 'markwang access', description: 'The ID of the AWS credentials to use')
        string(name: 'GIT_BRANCH', defaultValue: 'feature/devops-mark2', description: 'The Git branch to build and deploy')
    }
    stages {
        stage('IAC_management') {
            steps {
                script {
                    withCredentials([ 
                        [$class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: params.AWS_CREDENTIAL_ID,
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']
                    ]) {
                        // Clone the repository and checkout the correct branch
                        git branch: params.GIT_BRANCH, url: 'https://github.com/TechScrumTeamBeta/DevOps.git'
                        
                        // Change to the correct directory
                        dir('IAC_pipeline_test') {
                            sh 'terraform init'
                            sh 'terraform plan'
                            sh 'terraform apply --auto-approve'
                        }
                    }
                }
            }
        }
    }
}
